// 内置食物库：170+ 种常见食物的默认单位和每单位热量。
// 数据按食物类别分组，便于维护和扩展。
export const FOODS = [
  // === 主食类 ===
  { name: '包子', aliases: ['包子', '肉包子', '大包子', '小笼包'], defaultUnit: '个', caloriesPerUnit: 220 },
  { name: '鸡蛋', aliases: ['鸡蛋', '蛋', '水煮蛋', '煮鸡蛋', '荷包蛋', '煎蛋', '茶叶蛋', '卤蛋', '蒸蛋', '炒蛋'], defaultUnit: '个', caloriesPerUnit: 70 },
  { name: '牛奶', aliases: ['牛奶', '纯牛奶', '鲜牛奶'], defaultUnit: '盒', caloriesPerUnit: 150 },
  { name: '米饭', aliases: ['米饭', '饭', '白米饭', '大米饭'], defaultUnit: '碗', caloriesPerUnit: 230 },
  { name: '小米粥', aliases: ['小米粥', '粥', '白粥', '皮蛋粥'], defaultUnit: '碗', caloriesPerUnit: 90 },
  { name: '面条', aliases: ['面条', '面', '挂面', '拉面', '意面', '意大利面', '刀削面', '重庆小面', '牛肉面'], defaultUnit: '碗', caloriesPerUnit: 280 },
  { name: '馒头', aliases: ['馒头', '白馒头', '全麦馒头'], defaultUnit: '个', caloriesPerUnit: 220 },
  { name: '面包', aliases: ['面包', '吐司', '切片面包', '全麦面包'], defaultUnit: '片', caloriesPerUnit: 80 },
  { name: '三明治', aliases: ['三明治'], defaultUnit: '个', caloriesPerUnit: 350 },
  { name: '汉堡', aliases: ['汉堡', '汉堡包'], defaultUnit: '个', caloriesPerUnit: 500 },
  { name: '披萨', aliases: ['披萨', '比萨'], defaultUnit: '块', caloriesPerUnit: 280 },
  { name: '饺子', aliases: ['饺子', '水饺', '蒸饺'], defaultUnit: '个', caloriesPerUnit: 45 },
  { name: '馄饨', aliases: ['馄饨', '抄手'], defaultUnit: '个', caloriesPerUnit: 35 },
  { name: '烧麦', aliases: ['烧麦'], defaultUnit: '个', caloriesPerUnit: 100 },
  { name: '煎饼', aliases: ['煎饼', '煎饼果子'], defaultUnit: '个', caloriesPerUnit: 350 },
  { name: '油条', aliases: ['油条'], defaultUnit: '根', caloriesPerUnit: 200 },
  { name: '炒面', aliases: ['炒面', '干炒牛河'], defaultUnit: '份', caloriesPerUnit: 600 },
  { name: '炒饭', aliases: ['炒饭', '扬州炒饭'], defaultUnit: '碗', caloriesPerUnit: 500 },
  { name: '米粉', aliases: ['米粉', '米线'], defaultUnit: '碗', caloriesPerUnit: 350 },

  // === 蛋白质类 ===
  { name: '鸡胸肉', aliases: ['鸡胸肉', '鸡胸', '鸡脯'], defaultUnit: 'g', caloriesPerUnit: 1.65 },
  { name: '鸡腿', aliases: ['鸡腿', '炸鸡腿', '烤鸡腿'], defaultUnit: '个', caloriesPerUnit: 180 },
  { name: '鸡翅', aliases: ['鸡翅', '烤鸡翅'], defaultUnit: '个', caloriesPerUnit: 90 },
  { name: '鸡肉', aliases: ['鸡肉', '鸡'], defaultUnit: 'g', caloriesPerUnit: 1.65 },
  { name: '牛肉', aliases: ['牛肉', '酱牛肉', '卤牛肉'], defaultUnit: 'g', caloriesPerUnit: 2.50 },
  { name: '牛排', aliases: ['牛排', '煎牛排'], defaultUnit: '块', caloriesPerUnit: 300 },
  { name: '猪肉', aliases: ['猪肉', '五花肉', '里脊肉', '排骨'], defaultUnit: 'g', caloriesPerUnit: 2.43 },
  { name: '鱼肉', aliases: ['鱼肉', '鱼', '清蒸鱼'], defaultUnit: 'g', caloriesPerUnit: 1.20 },
  { name: '三文鱼', aliases: ['三文鱼', '鲑鱼'], defaultUnit: 'g', caloriesPerUnit: 2.08 },
  { name: '虾', aliases: ['虾', '虾仁', '基围虾', '大虾'], defaultUnit: 'g', caloriesPerUnit: 0.85 },
  { name: '豆腐', aliases: ['豆腐', '嫩豆腐', '老豆腐'], defaultUnit: 'g', caloriesPerUnit: 0.65 },
  { name: '豆浆', aliases: ['豆浆', '现磨豆浆', '甜豆浆', '咸豆浆'], defaultUnit: '杯', caloriesPerUnit: 60 },
  { name: '火腿肠', aliases: ['火腿肠'], defaultUnit: '根', caloriesPerUnit: 50 },
  { name: '香肠', aliases: ['香肠', '烤肠', '热狗'], defaultUnit: '根', caloriesPerUnit: 180 },
  { name: '培根', aliases: ['培根', '烟熏肉'], defaultUnit: '片', caloriesPerUnit: 45 },
  { name: '午餐肉', aliases: ['午餐肉'], defaultUnit: '片', caloriesPerUnit: 60 },
  { name: '鸡蛋灌饼', aliases: ['鸡蛋灌饼'], defaultUnit: '个', caloriesPerUnit: 380 },

  // === 蔬菜类 ===
  { name: '白菜', aliases: ['白菜'], defaultUnit: 'g', caloriesPerUnit: 0.13 },
  { name: '菠菜', aliases: ['菠菜'], defaultUnit: 'g', caloriesPerUnit: 0.23 },
  { name: '西兰花', aliases: ['西兰花'], defaultUnit: 'g', caloriesPerUnit: 0.34 },
  { name: '黄瓜', aliases: ['黄瓜'], defaultUnit: '根', caloriesPerUnit: 30 },
  { name: '西红柿', aliases: ['西红柿', '番茄'], defaultUnit: '个', caloriesPerUnit: 20 },
  { name: '胡萝卜', aliases: ['胡萝卜'], defaultUnit: '根', caloriesPerUnit: 40 },
  { name: '土豆', aliases: ['土豆', '马铃薯'], defaultUnit: '个', caloriesPerUnit: 80 },
  { name: '茄子', aliases: ['茄子'], defaultUnit: '个', caloriesPerUnit: 30 },
  { name: '青椒', aliases: ['青椒'], defaultUnit: '个', caloriesPerUnit: 20 },
  { name: '生菜', aliases: ['生菜'], defaultUnit: 'g', caloriesPerUnit: 0.15 },
  { name: '洋葱', aliases: ['洋葱'], defaultUnit: '个', caloriesPerUnit: 40 },
  { name: '蘑菇', aliases: ['蘑菇', '香菇'], defaultUnit: 'g', caloriesPerUnit: 0.22 },
  { name: '海带', aliases: ['海带'], defaultUnit: 'g', caloriesPerUnit: 0.12 },
  { name: '豆芽', aliases: ['豆芽'], defaultUnit: 'g', caloriesPerUnit: 0.16 },
  { name: '芹菜', aliases: ['芹菜'], defaultUnit: 'g', caloriesPerUnit: 0.14 },

  // === 水果类 ===
  { name: '苹果', aliases: ['苹果', '大苹果', '小苹果', '红苹果', '青苹果'], defaultUnit: '个', caloriesPerUnit: 95 },
  { name: '香蕉', aliases: ['香蕉', '大香蕉'], defaultUnit: '根', caloriesPerUnit: 105 },
  { name: '橙子', aliases: ['橙子', '脐橙'], defaultUnit: '个', caloriesPerUnit: 80 },
  { name: '葡萄', aliases: ['葡萄', '提子'], defaultUnit: 'g', caloriesPerUnit: 0.67 },
  { name: '西瓜', aliases: ['西瓜'], defaultUnit: '块', caloriesPerUnit: 80 },
  { name: '草莓', aliases: ['草莓'], defaultUnit: 'g', caloriesPerUnit: 0.32 },
  { name: '梨', aliases: ['梨', '雪梨'], defaultUnit: '个', caloriesPerUnit: 85 },
  { name: '桃子', aliases: ['桃子', '水蜜桃'], defaultUnit: '个', caloriesPerUnit: 70 },
  { name: '樱桃', aliases: ['樱桃'], defaultUnit: 'g', caloriesPerUnit: 0.63 },
  { name: '猕猴桃', aliases: ['猕猴桃', '奇异果'], defaultUnit: '个', caloriesPerUnit: 60 },
  { name: '芒果', aliases: ['芒果'], defaultUnit: '个', caloriesPerUnit: 100 },
  { name: '柠檬', aliases: ['柠檬'], defaultUnit: '个', caloriesPerUnit: 20 },
  { name: '火龙果', aliases: ['火龙果'], defaultUnit: '个', caloriesPerUnit: 150 },
  { name: '蓝莓', aliases: ['蓝莓'], defaultUnit: 'g', caloriesPerUnit: 0.57 },
  { name: '柚子', aliases: ['柚子'], defaultUnit: '瓣', caloriesPerUnit: 40 },

  // === 零食类 ===
  { name: '奥利奥', aliases: ['奥利奥', '奥利奥饼干'], defaultUnit: '个', caloriesPerUnit: 53 },
  { name: '辣条', aliases: ['辣条'], defaultUnit: '包', caloriesPerUnit: 300 },
  { name: '芒果干', aliases: ['芒果干'], defaultUnit: '片', caloriesPerUnit: 45 },
  { name: '虾条', aliases: ['虾条'], defaultUnit: '份', caloriesPerUnit: 120 },
  { name: '薯片', aliases: ['薯片', '薯条', '土豆片'], defaultUnit: '包', caloriesPerUnit: 350 },
  { name: '巧克力', aliases: ['巧克力', '黑巧克力', '牛奶巧克力'], defaultUnit: '块', caloriesPerUnit: 80 },
  { name: '糖果', aliases: ['糖果', '糖'], defaultUnit: '颗', caloriesPerUnit: 20 },
  { name: '饼干', aliases: ['饼干', '曲奇'], defaultUnit: '片', caloriesPerUnit: 50 },
  { name: '坚果', aliases: ['坚果', '核桃', '杏仁', '腰果', '开心果'], defaultUnit: 'g', caloriesPerUnit: 6.00 },
  { name: '瓜子', aliases: ['瓜子', '葵花籽'], defaultUnit: 'g', caloriesPerUnit: 5.50 },
  { name: '爆米花', aliases: ['爆米花'], defaultUnit: '份', caloriesPerUnit: 200 },
  { name: '蛋糕', aliases: ['蛋糕', '奶油蛋糕', '慕斯蛋糕'], defaultUnit: '块', caloriesPerUnit: 350 },
  { name: '甜甜圈', aliases: ['甜甜圈', '多拿滋'], defaultUnit: '个', caloriesPerUnit: 300 },
  { name: '冰淇淋', aliases: ['冰淇淋', '雪糕', '冰棍'], defaultUnit: '个', caloriesPerUnit: 200 },
  { name: '果冻', aliases: ['果冻'], defaultUnit: '个', caloriesPerUnit: 60 },
  { name: '山楂片', aliases: ['山楂片'], defaultUnit: '片', caloriesPerUnit: 15 },
  { name: '海苔', aliases: ['海苔'], defaultUnit: '包', caloriesPerUnit: 30 },
  { name: '牛肉干', aliases: ['牛肉干'], defaultUnit: 'g', caloriesPerUnit: 3.50 },
  { name: '猪肉脯', aliases: ['猪肉脯'], defaultUnit: '片', caloriesPerUnit: 40 },

  // === 饮料类 ===
  { name: '可乐', aliases: ['可乐', '可口可乐', '百事可乐'], defaultUnit: '瓶', caloriesPerUnit: 210 },
  { name: '雪碧', aliases: ['雪碧'], defaultUnit: '瓶', caloriesPerUnit: 200 },
  { name: '芬达', aliases: ['芬达'], defaultUnit: '瓶', caloriesPerUnit: 200 },
  { name: '奶茶', aliases: ['奶茶', '珍珠奶茶', '椰果奶茶'], defaultUnit: '杯', caloriesPerUnit: 350 },
  { name: '咖啡', aliases: ['咖啡', '美式咖啡', '拿铁', '卡布奇诺', '摩卡'], defaultUnit: '杯', caloriesPerUnit: 5 },
  { name: '拿铁', aliases: ['拿铁'], defaultUnit: '杯', caloriesPerUnit: 150 },
  { name: '摩卡', aliases: ['摩卡'], defaultUnit: '杯', caloriesPerUnit: 300 },
  { name: '酸奶', aliases: ['酸奶', '酸牛奶', '希腊酸奶'], defaultUnit: '盒', caloriesPerUnit: 120 },
  { name: '果汁', aliases: ['果汁', '橙汁', '苹果汁', '葡萄汁'], defaultUnit: '杯', caloriesPerUnit: 120 },
  { name: '啤酒', aliases: ['啤酒'], defaultUnit: '瓶', caloriesPerUnit: 150 },
  { name: '红酒', aliases: ['红酒'], defaultUnit: '杯', caloriesPerUnit: 120 },
  { name: '白酒', aliases: ['白酒'], defaultUnit: '杯', caloriesPerUnit: 100 },
  { name: '功能饮料', aliases: ['功能饮料', '红牛', '脉动'], defaultUnit: '瓶', caloriesPerUnit: 120 },
  { name: '水', aliases: ['水', '矿泉水', '纯净水'], defaultUnit: '瓶', caloriesPerUnit: 0 },
  { name: '绿茶', aliases: ['绿茶', '龙井', '碧螺春'], defaultUnit: '杯', caloriesPerUnit: 2 },
  { name: '红茶', aliases: ['红茶'], defaultUnit: '杯', caloriesPerUnit: 2 },
  { name: '乌龙茶', aliases: ['乌龙茶'], defaultUnit: '杯', caloriesPerUnit: 2 },
  { name: '花茶', aliases: ['花茶', '菊花茶'], defaultUnit: '杯', caloriesPerUnit: 2 },

  // === 外卖/快餐 ===
  { name: '盖浇饭', aliases: ['盖浇饭', '盖饭'], defaultUnit: '份', caloriesPerUnit: 650 },
  { name: '黄焖鸡', aliases: ['黄焖鸡', '黄焖鸡米饭'], defaultUnit: '份', caloriesPerUnit: 700 },
  { name: '麻辣烫', aliases: ['麻辣烫'], defaultUnit: '份', caloriesPerUnit: 600 },
  { name: '麻辣香锅', aliases: ['麻辣香锅'], defaultUnit: '份', caloriesPerUnit: 750 },
  { name: '酸菜鱼', aliases: ['酸菜鱼'], defaultUnit: '份', caloriesPerUnit: 550 },
  { name: '水煮鱼', aliases: ['水煮鱼'], defaultUnit: '份', caloriesPerUnit: 600 },
  { name: '宫保鸡丁', aliases: ['宫保鸡丁'], defaultUnit: '份', caloriesPerUnit: 400 },
  { name: '麻婆豆腐', aliases: ['麻婆豆腐'], defaultUnit: '份', caloriesPerUnit: 300 },
  { name: '鱼香肉丝', aliases: ['鱼香肉丝'], defaultUnit: '份', caloriesPerUnit: 350 },
  { name: '回锅肉', aliases: ['回锅肉'], defaultUnit: '份', caloriesPerUnit: 500 },
  { name: '糖醋排骨', aliases: ['糖醋排骨'], defaultUnit: '份', caloriesPerUnit: 450 },
  { name: '红烧肉', aliases: ['红烧肉'], defaultUnit: '份', caloriesPerUnit: 500 },
  { name: '小鸡炖蘑菇', aliases: ['小鸡炖蘑菇'], defaultUnit: '份', caloriesPerUnit: 450 },
  { name: '西红柿炒蛋', aliases: ['西红柿炒蛋', '番茄炒蛋'], defaultUnit: '份', caloriesPerUnit: 250 },
  { name: '地三鲜', aliases: ['地三鲜'], defaultUnit: '份', caloriesPerUnit: 350 },
  { name: '京酱肉丝', aliases: ['京酱肉丝'], defaultUnit: '份', caloriesPerUnit: 400 },
  { name: '水煮肉片', aliases: ['水煮肉片'], defaultUnit: '份', caloriesPerUnit: 450 },
  { name: '炸酱面', aliases: ['炸酱面'], defaultUnit: '碗', caloriesPerUnit: 450 },
  { name: '兰州拉面', aliases: ['兰州拉面'], defaultUnit: '碗', caloriesPerUnit: 500 },
  { name: '热干面', aliases: ['热干面'], defaultUnit: '碗', caloriesPerUnit: 480 },
  { name: '重庆小面', aliases: ['重庆小面'], defaultUnit: '碗', caloriesPerUnit: 500 },
  { name: '螺蛳粉', aliases: ['螺蛳粉'], defaultUnit: '碗', caloriesPerUnit: 550 },
  { name: '酸辣粉', aliases: ['酸辣粉'], defaultUnit: '碗', caloriesPerUnit: 400 },
  { name: '烤冷面', aliases: ['烤冷面'], defaultUnit: '份', caloriesPerUnit: 350 },
  { name: '手抓饼', aliases: ['手抓饼'], defaultUnit: '个', caloriesPerUnit: 400 },
  { name: '烤串', aliases: ['烤串', '羊肉串', '烤羊肉串'], defaultUnit: '串', caloriesPerUnit: 80 },
  { name: '寿司', aliases: ['寿司'], defaultUnit: '个', caloriesPerUnit: 40 },
  { name: '沙拉', aliases: ['沙拉', '蔬菜沙拉'], defaultUnit: '份', caloriesPerUnit: 150 },
  { name: '关东煮', aliases: ['关东煮'], defaultUnit: '份', caloriesPerUnit: 300 },
  { name: '方便面', aliases: ['方便面', '泡面', '速食面'], defaultUnit: '包', caloriesPerUnit: 450 },
  { name: '自热火锅', aliases: ['自热火锅'], defaultUnit: '份', caloriesPerUnit: 600 },

  // === 其他 ===
  { name: '蛋白粉', aliases: ['蛋白粉', '乳清蛋白'], defaultUnit: '勺', caloriesPerUnit: 120 },
  { name: '燕麦', aliases: ['燕麦', '燕麦片'], defaultUnit: 'g', caloriesPerUnit: 3.89 },
  { name: '玉米', aliases: ['玉米', '甜玉米'], defaultUnit: '根', caloriesPerUnit: 120 },
  { name: '红薯', aliases: ['红薯', '地瓜', '烤红薯'], defaultUnit: '个', caloriesPerUnit: 130 },
  { name: '紫薯', aliases: ['紫薯'], defaultUnit: '个', caloriesPerUnit: 110 },
  { name: '藕', aliases: ['藕', '莲藕'], defaultUnit: 'g', caloriesPerUnit: 0.47 },
  { name: '银耳', aliases: ['银耳', '白木耳'], defaultUnit: 'g', caloriesPerUnit: 0.26 },
  { name: '枸杞', aliases: ['枸杞'], defaultUnit: 'g', caloriesPerUnit: 2.80 },
  { name: '红枣', aliases: ['红枣', '大枣'], defaultUnit: '颗', caloriesPerUnit: 30 },
  { name: '桂圆', aliases: ['桂圆', '龙眼'], defaultUnit: '颗', caloriesPerUnit: 15 },
  { name: '核桃', aliases: ['核桃'], defaultUnit: '个', caloriesPerUnit: 40 },
  { name: '芝麻', aliases: ['芝麻', '黑芝麻'], defaultUnit: 'g', caloriesPerUnit: 5.80 },
  { name: '花生', aliases: ['花生'], defaultUnit: 'g', caloriesPerUnit: 5.67 },
  { name: '黄油', aliases: ['黄油'], defaultUnit: 'g', caloriesPerUnit: 7.17 },
  { name: '芝士', aliases: ['芝士', '奶酪', '起司'], defaultUnit: '片', caloriesPerUnit: 70 },
  { name: '沙拉酱', aliases: ['沙拉酱'], defaultUnit: '勺', caloriesPerUnit: 90 },
  { name: '番茄酱', aliases: ['番茄酱', '番茄沙司'], defaultUnit: '勺', caloriesPerUnit: 15 },
  { name: '辣椒酱', aliases: ['辣椒酱'], defaultUnit: '勺', caloriesPerUnit: 20 },
  { name: '花生酱', aliases: ['花生酱'], defaultUnit: '勺', caloriesPerUnit: 95 },
  { name: '果酱', aliases: ['果酱'], defaultUnit: '勺', caloriesPerUnit: 50 },
  { name: '蜂蜜', aliases: ['蜂蜜'], defaultUnit: '勺', caloriesPerUnit: 60 },
  { name: '橄榄油', aliases: ['橄榄油'], defaultUnit: '勺', caloriesPerUnit: 120 },
  { name: '酱油', aliases: ['酱油'], defaultUnit: '勺', caloriesPerUnit: 5 },
  { name: '醋', aliases: ['醋'], defaultUnit: '勺', caloriesPerUnit: 3 },
];
